{{- if .Values.rbac.enabled }}
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "parca-operator.rbacName" . }}
  labels:
    {{- include "parca-operator.labels" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: {{ include "parca-operator.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: {{ include "parca-operator.rbacName" . }}
  apiGroup: rbac.authorization.k8s.io
{{- end }}
