{{- if .Values.serviceAccount.enabled -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "parca-operator.serviceAccountName" . }}
  labels:
    {{- include "parca-operator.labels" . | nindent 4 }}
{{- end }}
